#ifndef _SYS_SYSCALL_H
#define _SYS_SYSCALL_H

#define __NR_readv		0
#define __NR_writev		1
#define __NR_lseek		2
#define __NR_close		3
#define __NR_openat		4
#define __NR_mkdirat		5
#define __NR_linkat		6
#define __NR_unlinkat		7
#define __NR_getdents		8
#define __NR_getcreds		9
#define __NR_kill		10
#define __NR_exit		11
#define __NR_sigaction		12
#define __NR_mmap		13
#define __NR_munmap		14
#define __NR_mprotect		15
#define __NR_fork		16
#define __NR_execve		17
#define __NR_waitpid		18
#define __NR_gettime		19
#define __NR_nanosleep		20
#define __NR_fstatat		21
#define __NR_pipe		22
#define __NR_chdirat		23
#define __NR_dup		24
#define __NR_dup2		25
#define __NR_getcwd		26
#define __NR_fcntl		27
#define __NR_setcreds		28
#define __NR_setgroups		29
#define __NR_mount		30
#define __NR_faccessat		31
#define __NR_uname		32
#define __NR_sethostname	33
#define __NR_chrootat		34
#define __NR_mknodat		35
#define __NR_brk		36
#define __NR_utimensat		37
#define __NR_ioctl		38

#endif
#define SYS_readv		0
#define SYS_writev		1
#define SYS_lseek		2
#define SYS_close		3
#define SYS_openat		4
#define SYS_mkdirat		5
#define SYS_linkat		6
#define SYS_unlinkat		7
#define SYS_getdents		8
#define SYS_getcreds		9
#define SYS_kill		10
#define SYS_exit		11
#define SYS_sigaction		12
#define SYS_mmap		13
#define SYS_munmap		14
#define SYS_mprotect		15
#define SYS_fork		16
#define SYS_execve		17
#define SYS_waitpid		18
#define SYS_gettime		19
#define SYS_nanosleep		20
#define SYS_fstatat		21
#define SYS_pipe		22
#define SYS_chdirat		23
#define SYS_dup		24
#define SYS_dup2		25
#define SYS_getcwd		26
#define SYS_fcntl		27
#define SYS_setcreds		28
#define SYS_setgroups		29
#define SYS_mount		30
#define SYS_faccessat		31
#define SYS_uname		32
#define SYS_sethostname	33
#define SYS_chrootat		34
#define SYS_mknodat		35
#define SYS_brk		36
#define SYS_utimensat		37
#define SYS_ioctl		38
