#pragma once

#define ENOMEM 1
#define EOVERFLOW 2
#define EUNDERFLOW 3
#define EINVAL 4
#define EEXIST 5
#define ENOTSUP 6
#define ENOENT 7
#define EBUSY 8
#define EPERM 9
#define EIO 10
#define ENXIO 11
#define E2BIG 12
#define EACCES 13
#define EFAULT 14
#define ENODEV 15
#define ENOTDIR 16
#define EISDIR 17
#define EFBIG 18
#define ENOSPC 19
#define EROFS 20
#define EMLINK 21
#define ERANGE 22
#define ENOTEMPTY 23
#define ENODATA 24
#define ENOEXEC 24
#define ENOSYS 25
#define EBADF 26
#define ECONNREFUSED 27
#define ECANCELED 28
#define ETIMEDOUT 29
#define EINTR 30
#define EAGAIN 31
