#!/bin/sh
export PATH=/bin:/usr/bin:/sbin:/usr/sbin
info() {
        echo $*
}

cat <<"EOF"

           welcome to
 _                       _      
| |__  _   _ _ __  _ __ (_)_  __
| '_ \| | | | '_ \| '_ \| \ \/ /
| |_) | |_| | | | | | | | |>  < 
|_.__/ \__,_|_| |_|_| |_|_/_/\_\

EOF

info "Booting Bunnix userspace"

if [ -e /etc/hostname ]
then
	info "Set system hostname"
	hostname $(cat /etc/hostname)
fi

info "Mounting filesystems"
while read dev mnt fstype
do
	mount -t $fstype $dev $mnt
done </etc/fstab

info "Starting user sessions"

echo
for tty in /dev/tty*
do
	getty $tty &
done
