#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
info() {
        echo $*
}

cat <<"EOF"

           welcome to

EOF
cat /etc/banner

info "Booting Bunnix userspace"

if [ -e /etc/hostname ]
then
	info "Set system hostname"
	hostname $(cat /etc/hostname)
fi

info "Mounting filesystems"
while read dev mnt fstype
do
	mount -t $fstype $dev $mnt
done </etc/fstab

info "Starting user sessions"

session() {
	while :
	do
		getty $1
	done
}

echo
for tty in /dev/tty*
do
	# skip /dev/tty psuedo-device
	[ "$tty" = "/dev/tty" ] && continue

	session $tty &
done
