/* The first entry is a catch-all for codes not enumerated here.
 * This file is included multiple times to declare and define a structure
 * with these messages, and then to define a lookup table translating
 * error codes to offsets of corresponding fields in the structure. */

E(0,            	"No error information")
E(ENOMEM,       	"Out of memory")
E(EOVERFLOW,    	"Value too large for data type")
E(EUNDERFLOW,   	"Value too small for data type")
E(EINVAL,       	"Invalid argument")
E(EEXIST,       	"File exists")
E(ENOTSUP,      	"Not supported")
E(ENOENT,       	"No such file or directory")
E(EBUSY,        	"Resource busy")
E(EPERM,        	"Operation not permitted")
E(EIO,          	"I/O error")
E(ENXIO,        	"No such device or address")
E(E2BIG,        	"Argument list too long")
E(EACCES,       	"Permission denied")
E(EFAULT,       	"Bad address")
E(ENODEV,       	"No such device")
E(ENOTDIR,      	"Not a directory")
E(EISDIR,       	"Is a directory")
E(EFBIG,        	"File too large")
E(ENOSPC,       	"No space left on device")
E(EROFS,        	"Read-only file system")
E(EMLINK,       	"Too many links")
E(ERANGE,       	"Result not representable")
E(ENOTEMPTY,    	"Directory not empty")
E(ENODATA,      	"No data available")
E(ENOEXEC,      	"Exec format error")
E(ENOSYS,       	"Function not implemented")
E(EBADF,        	"Bad file descriptor")
E(ECONNREFUSED, 	"Connection refused")
E(ECANCELED,    	"Operation canceled")
E(ETIMEDOUT,    	"Operation timed out")
E(EINTR,        	"Interrupted system call")
E(EAGAIN,       	"Resource temporarily unavailable")
E(ECHILD,       	"No child process")
E(ENAMETOOLONG,		"Filename too long")
E(EADDRINUSE,		"Address in use")
E(EADDRNOTAVAIL,	"Address not available")
E(EAFNOSUPPORT,		"Address family not supported by protocol")
E(EALREADY,		"Operation already in progress")
E(ECONNRESET,		"Connection reset by peer")
E(EDEADLK,		"Resource deadlock would occur")
E(EDESTADDRREQ,		"Destination address required")
E(EDOM,			"Domain error")
E(EHOSTUNREACH,		"Host is unreachable")
E(EINPROGRESS,		"Operation in progress")
E(EISCONN,		"Socket is connected")
E(ELOOP,		"Symbolic link loop")
E(EMFILE,		"No file descriptors available")
E(EMSGSIZE,		"Message too large")
E(ENETDOWN,		"Network is down")
E(ENETRESET,		"Connection reset by network")
E(ENETUNREACH,		"Network unreachable")
E(ENFILE,		"Too many open files in system")
E(ENOBUFS,		"No buffer space available")
E(ENOPROTOOPT,		"Protocol not available")
E(ENOTCONN,		"Socket not connected")
E(ENOTSOCK,		"Not a socket")
E(ENOTTY,		"Not a tty")
E(EPIPE,		"Broken pipe")
E(EPROTONOSUPPORT,	"Protocol not supported")
E(EPROTOTYPE,		"Protocol wrong type for socket")
E(ESPIPE,		"Invalid seek")
E(ESRCH,		"No such process")
E(EWOULDBLOCK,		"Resource temporarily unavailable")
E(EXDEV,		"Cross-device link")
E(ECONNABORTED,		"Connection aborted")
E(ENOLCK,		"No locks available")
E(EOPNOTSUPP,		"Not supported")

// libc-internal errors

E(EILSEQ,       "Illegal byte sequence")
E(ENOMSG,       "No message of desired type")
