#!/bin/sh
root=/

while getopts r: name
do
	case name in
	C)
		root="$OPTARG"
		;;
	?)
		echo "Usage: $0 [-C root] [packages...]"
		;;
	esac
done
shift $(($OPTIND - 1))

install() {
	local pkg=$1
	if ! [ -e /dist/$pkg.tar.gz ]
	then
		echo "No such package $pkg"
		exit 1
	fi
	printf "Install $pkg.tar.gz... "
	tar -C $root -xzf /dist/$pkg.tar.gz
	echo "ok"
}

for pkg in "$@"
do
	install $pkg
done
